name: qdrant
description: gRPC client for Qdrant
version: 1.0.1
repository: https://github.com/ArcaneArts/qdrant

environment:
  sdk: ^3.7.0
dependencies:
  fixnum: ^1.1.1
  grpc: ^4.0.4
  protobuf: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  test: ^1.24.0
scripts:
  build_runner: dart run build_runner build --delete-conflicting-outputs
  protocompile: protoc --proto_path=./proto --dart_out=grpc:lib/protobuf ./proto/*.proto
  protoc: dart pub global activate protoc_plugin